name: Docker Image Build & Push

on:
  push:
    paths:
    - _debug_dep/src/**

#env:
#  TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Dynamically set MY_DATE environment variable
    #  run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mightyfoxx/pub_debug:latest
   
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push mightyfoxx/pub_debug:latest
